# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "64c8979eae064cedff97462b76024b78"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
name = "checkout-treat"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2026-07"

[build]
automatically_update_urls_on_dev = true
